// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDACE9uE_YoZtF2E38Z0jjDkyFOQCBeTRs',
    appId: '1:1083194689692:web:8b0db72b7c98532dcdc559',
    messagingSenderId: '1083194689692',
    projectId: 'test-df08e',
    authDomain: 'test-df08e.firebaseapp.com',
    databaseURL: 'https://test-df08e-default-rtdb.firebaseio.com',
    storageBucket: 'test-df08e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ULrhAWAgGcnnbedAjuROvPExY4YsE3E',
    appId: '1:1083194689692:android:ffa449503e6c73e5cdc559',
    messagingSenderId: '1083194689692',
    projectId: 'test-df08e',
    databaseURL: 'https://test-df08e-default-rtdb.firebaseio.com',
    storageBucket: 'test-df08e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcmVLkJQmAgowmoBw35RF_hTdbKZwKYok',
    appId: '1:1083194689692:ios:e9292949cdf510d8cdc559',
    messagingSenderId: '1083194689692',
    projectId: 'test-df08e',
    databaseURL: 'https://test-df08e-default-rtdb.firebaseio.com',
    storageBucket: 'test-df08e.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcmVLkJQmAgowmoBw35RF_hTdbKZwKYok',
    appId: '1:1083194689692:ios:43cd075617eedfd6cdc559',
    messagingSenderId: '1083194689692',
    projectId: 'test-df08e',
    databaseURL: 'https://test-df08e-default-rtdb.firebaseio.com',
    storageBucket: 'test-df08e.appspot.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
